[project]
name = "eiti-soe-matcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fuzzywuzzy>=0.18.0",
    "requests>=2.32.3",
    "streamlit>=1.40.1",
    "unidecode>=1.3.8",
    "uuid>=1.30",
]
